import type { teamData } from "./types";

export const allTeamData: teamData[] = [
  {
    id: 133,
    full_name: "Athletics",
    abbreviation: "ATH",
    team_name: "Athletics",
  },
  {
    id: 134,
    full_name: "Pittsburgh Pirates",
    abbreviation: "PIT",
    team_name: "Pirates",
  },
  {
    id: 135,
    full_name: "San Diego Padres",
    abbreviation: "SD",
    team_name: "Padres",
  },
  {
    id: 136,
    full_name: "Seattle Mariners",
    abbreviation: "SEA",
    team_name: "Mariners",
  },
  {
    id: 137,
    full_name: "San Francisco Giants",
    abbreviation: "SF",
    team_name: "Giants",
  },
  {
    id: 138,
    full_name: "St. Louis Cardinals",
    abbreviation: "STL",
    team_name: "Cardinals",
  },
  {
    id: 139,
    full_name: "Tampa Bay Rays",
    abbreviation: "TB",
    team_name: "Rays",
  },
  {
    id: 140,
    full_name: "Texas Rangers",
    abbreviation: "TEX",
    team_name: "Rangers",
  },
  {
    id: 141,
    full_name: "Toronto Blue Jays",
    abbreviation: "TOR",
    team_name: "Blue Jays",
  },
  {
    id: 142,
    full_name: "Minnesota Twins",
    abbreviation: "MIN",
    team_name: "Twins",
  },
  {
    id: 143,
    full_name: "Philadelphia Phillies",
    abbreviation: "PHI",
    team_name: "Phillies",
  },
  {
    id: 144,
    full_name: "Atlanta Braves",
    abbreviation: "ATL",
    team_name: "Braves",
  },
  {
    id: 145,
    full_name: "Chicago White Sox",
    abbreviation: "CWS",
    team_name: "White Sox",
  },
  {
    id: 146,
    full_name: "Miami Marlins",
    abbreviation: "MIA",
    team_name: "Marlins",
  },
  {
    id: 147,
    full_name: "New York Yankees",
    abbreviation: "NYY",
    team_name: "Yankees",
  },
  {
    id: 158,
    full_name: "Milwaukee Brewers",
    abbreviation: "MIL",
    team_name: "Brewers",
  },
  {
    id: 108,
    full_name: "Los Angeles Angels",
    abbreviation: "LAA",
    team_name: "Angels",
  },
  {
    id: 109,
    full_name: "Arizona Diamondbacks",
    abbreviation: "AZ",
    team_name: "D-backs",
  },
  {
    id: 110,
    full_name: "Baltimore Orioles",
    abbreviation: "BAL",
    team_name: "Orioles",
  },
  {
    id: 111,
    full_name: "Boston Red Sox",
    abbreviation: "BOS",
    team_name: "Red Sox",
  },
  {
    id: 112,
    full_name: "Chicago Cubs",
    abbreviation: "CHC",
    team_name: "Cubs",
  },
  {
    id: 113,
    full_name: "Cincinnati Reds",
    abbreviation: "CIN",
    team_name: "Reds",
  },
  {
    id: 114,
    full_name: "Cleveland Guardians",
    abbreviation: "CLE",
    team_name: "Guardians",
  },
  {
    id: 115,
    full_name: "Colorado Rockies",
    abbreviation: "COL",
    team_name: "Rockies",
  },
  {
    id: 116,
    full_name: "Detroit Tigers",
    abbreviation: "DET",
    team_name: "Tigers",
  },
  {
    id: 117,
    full_name: "Houston Astros",
    abbreviation: "HOU",
    team_name: "Astros",
  },
  {
    id: 118,
    full_name: "Kansas City Royals",
    abbreviation: "KC",
    team_name: "Royals",
  },
  {
    id: 119,
    full_name: "Los Angeles Dodgers",
    abbreviation: "LAD",
    team_name: "Dodgers",
  },
  {
    id: 120,
    full_name: "Washington Nationals",
    abbreviation: "WSH",
    team_name: "Nationals",
  },
  {
    id: 121,
    full_name: "New York Mets",
    abbreviation: "NYM",
    team_name: "Mets",
  },
];
