import type { teamData } from "@/types/teamTypes";

export const allTeamData: teamData[] = [
  {
    id: 133,
    fullName: "Athletics",
    abbreviation: "ATH",
    shortName: "Athletics",
  },
  {
    id: 134,
    fullName: "Pittsburgh Pirates",
    abbreviation: "PIT",
    shortName: "Pirates",
  },
  {
    id: 135,
    fullName: "San Diego Padres",
    abbreviation: "SD",
    shortName: "Padres",
  },
  {
    id: 136,
    fullName: "Seattle Mariners",
    abbreviation: "SEA",
    shortName: "Mariners",
  },
  {
    id: 137,
    fullName: "San Francisco Giants",
    abbreviation: "SF",
    shortName: "Giants",
  },
  {
    id: 138,
    fullName: "St. Louis Cardinals",
    abbreviation: "STL",
    shortName: "Cardinals",
  },
  {
    id: 139,
    fullName: "Tampa Bay Rays",
    abbreviation: "TB",
    shortName: "Rays",
  },
  {
    id: 140,
    fullName: "Texas Rangers",
    abbreviation: "TEX",
    shortName: "Rangers",
  },
  {
    id: 141,
    fullName: "Toronto Blue Jays",
    abbreviation: "TOR",
    shortName: "Blue Jays",
  },
  {
    id: 142,
    fullName: "Minnesota Twins",
    abbreviation: "MIN",
    shortName: "Twins",
  },
  {
    id: 143,
    fullName: "Philadelphia Phillies",
    abbreviation: "PHI",
    shortName: "Phillies",
  },
  {
    id: 144,
    fullName: "Atlanta Braves",
    abbreviation: "ATL",
    shortName: "Braves",
  },
  {
    id: 145,
    fullName: "Chicago White Sox",
    abbreviation: "CWS",
    shortName: "White Sox",
  },
  {
    id: 146,
    fullName: "Miami Marlins",
    abbreviation: "MIA",
    shortName: "Marlins",
  },
  {
    id: 147,
    fullName: "New York Yankees",
    abbreviation: "NYY",
    shortName: "Yankees",
  },
  {
    id: 158,
    fullName: "Milwaukee Brewers",
    abbreviation: "MIL",
    shortName: "Brewers",
  },
  {
    id: 108,
    fullName: "Los Angeles Angels",
    abbreviation: "LAA",
    shortName: "Angels",
  },
  {
    id: 109,
    fullName: "Arizona Diamondbacks",
    abbreviation: "AZ",
    shortName: "D-backs",
  },
  {
    id: 110,
    fullName: "Baltimore Orioles",
    abbreviation: "BAL",
    shortName: "Orioles",
  },
  {
    id: 111,
    fullName: "Boston Red Sox",
    abbreviation: "BOS",
    shortName: "Red Sox",
  },
  {
    id: 112,
    fullName: "Chicago Cubs",
    abbreviation: "CHC",
    shortName: "Cubs",
  },
  {
    id: 113,
    fullName: "Cincinnati Reds",
    abbreviation: "CIN",
    shortName: "Reds",
  },
  {
    id: 114,
    fullName: "Cleveland Guardians",
    abbreviation: "CLE",
    shortName: "Guardians",
  },
  {
    id: 115,
    fullName: "Colorado Rockies",
    abbreviation: "COL",
    shortName: "Rockies",
  },
  {
    id: 116,
    fullName: "Detroit Tigers",
    abbreviation: "DET",
    shortName: "Tigers",
  },
  {
    id: 117,
    fullName: "Houston Astros",
    abbreviation: "HOU",
    shortName: "Astros",
  },
  {
    id: 118,
    fullName: "Kansas City Royals",
    abbreviation: "KC",
    shortName: "Royals",
  },
  {
    id: 119,
    fullName: "Los Angeles Dodgers",
    abbreviation: "LAD",
    shortName: "Dodgers",
  },
  {
    id: 120,
    fullName: "Washington Nationals",
    abbreviation: "WSH",
    shortName: "Nationals",
  },
  {
    id: 121,
    fullName: "New York Mets",
    abbreviation: "NYM",
    shortName: "Mets",
  },
];
